version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/tools/php"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: "npm"
    directory: "/tools/js"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: 'fix(deps): '
    groups:
      all:
        patterns:
          - '*'  