name: Docker Build

on:
    push:
        branches: [ main ]

jobs:
    build:
        strategy:
          matrix:
            include:
              - runner: ubuntu-24.04
                arch: amd64
              - runner: ubuntu-24.04-arm
                arch: arm64
        runs-on: ${{ matrix.runner }}
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: |
                    ghcr.io/shopwarelabs/extension-verifier:${{ matrix.arch }}
                cache-from: type=gha,scope=${{ matrix.arch }}
                cache-to: type=gha,scope=${{ matrix.arch }},mode=max
                provenance: false

    merge:
        runs-on: ubuntu-24.04
        needs: build
        steps:
          - name: Log in to registry
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - run: |
                docker manifest create ghcr.io/shopwarelabs/extension-verifier:latest \
                    ghcr.io/shopwarelabs/extension-verifier:amd64 \
                    ghcr.io/shopwarelabs/extension-verifier:arm64
                docker manifest push ghcr.io/shopwarelabs/extension-verifier:latest
