name: Docker Build

on:
    push:
        branches:
          - main
        tags:
          - '*'
jobs:
    build:
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ghcr.io/shopwarelabs/extension-verifier
                tags: |
                  # For branches, use the branch name
                  type=ref,event=branch
                  # For tags, use the tag name
                  type=ref,event=tag
                  # Set latest tag for main branch and tags
                  type=raw,value=latest,enable={{startsWith(github.ref, 'refs/tags/')}}

            - name: Log in to registry
              uses: docker/login-action@v3
              with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                platforms: linux/amd64,linux/arm64
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
                provenance: false
