name: golangci-lint
on:
  workflow_dispatch:
  push:
    tags-ignore:
      - "*"
    branches:
      - main
    paths:
      - '*.go'
      - '**/*.go'
      - '.github/workflows/lint.yml'
  pull_request:
    paths:
      - '*.go'
      - '**/*.go'
      - '.github/workflows/lint.yml'

permissions:
  contents: read

env:
  GOTOOLCHAIN: local

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # ratchet:step-security/harden-runner@v2.12.0
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            golangci-lint.run:443
            objects.githubusercontent.com:443
            proxy.golang.org:443
            raw.githubusercontent.com:443
            storage.googleapis.com:443

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # ratchet:actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # ratchet:golangci/golangci-lint-action@v6
        with:
          version: latest
          args: --timeout 4m
